version: "3.7"
# ローカル環境での稼働確認用
services:     
    web:
        # buildはせず、存在するdocker imageを利用するよう指定
        image: yakitori99/trip-weather-frontend:v0.1.1
        ports:
            # web server
            - 5000:80
        # ホストOSの起動時、コンテナの不慮の停止時などにコンテナを自動起動するよう指定
        restart: always