export default {
  // DICT
  UPDATE_CITY_CODE_NAME_DICT      : 'UPDATE_CITY_CODE_NAME_DICT',
  UPDATE_PREF_CODE_CITY_INFOS_DICT: 'UPDATE_PREF_CODE_CITY_INFOS_DICT',
  // FROM
  UPDATE_ITEMS_FROM_PREF        : 'UPDATE_ITEMS_FROM_PREF',
  UPDATE_ITEM_FROM_PREF_SELECTED: 'UPDATE_ITEM_FROM_PREF_SELECTED',
  UPDATE_ITEMS_FROM_CITY        : 'UPDATE_ITEMS_FROM_CITY',
  UPDATE_ITEM_FROM_CITY_SELECTED: 'UPDATE_ITEM_FROM_CITY_SELECTED',
  UPDATE_FROM_CITY_NAME         : 'UPDATE_FROM_CITY_NAME',
  // TO
  UPDATE_ITEMS_TO_PREF        : 'UPDATE_ITEMS_TO_PREF',
  UPDATE_ITEM_TO_PREF_SELECTED: 'UPDATE_ITEM_TO_PREF_SELECTED',
  UPDATE_ITEMS_TO_CITY        : 'UPDATE_ITEMS_TO_CITY',
  UPDATE_ITEM_TO_CITY_SELECTED: 'UPDATE_ITEM_TO_CITY_SELECTED',
  UPDATE_TO_CITY_NAME         : 'UPDATE_TO_CITY_NAME',
  // CHART LABEL
  UPDATE_LABEL_DATES  : 'UPDATE_LABEL_DATES',
  UPDATE_FROM_WEATHERS: 'UPDATE_FROM_WEATHERS',
  UPDATE_TO_WEATHERS  : 'UPDATE_TO_WEATHERS',
  // CHART DATA
  UPDATE_FROM_TEMP_MAXS: 'UPDATE_FROM_TEMP_MAXS',
  UPDATE_FROM_TEMP_MINS: 'UPDATE_FROM_TEMP_MINS',
  UPDATE_TO_TEMP_MAXS  : 'UPDATE_TO_TEMP_MAXS',
  UPDATE_TO_TEMP_MINS  : 'UPDATE_TO_TEMP_MINS',
}
